"""
Dimcause Lint - Project Integrity Checker

核心检查项 (V0.9):
1. 任务卡完整性: STATUS 中的任务 ID 是否在 agent-tasks 中有对应文件
2. 状态证据链: STATUS 中标为 Done 的任务是否有代码/测试存在
3. 规则文件合法性: .mdc 文件的 YAML frontmatter 是否完整
4. CLI 实现验证: D1/T1/H1 对应的 CLI 命令是否存在
5. 文件路径存在性: 任务卡中引用的文件路径是否真实存在
"""

import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import List, Optional

from dimcause.scheduler.status_files import (
    MODERN_STATUS_FILE as MODERN_STATUS_PATH,
)
from dimcause.scheduler.status_files import (
    extract_compact_task_ids,
    resolve_status_file,
)


class Severity(Enum):
    """问题严重程度"""

    ERROR = "error"  # 必须修复
    WARNING = "warning"  # 建议修复
    INFO = "info"  # 仅供参考


@dataclass
class LintIssue:
    """Lint 问题"""

    check: str  # 检查项名称
    severity: Severity
    message: str
    file_path: Optional[Path] = None
    suggestion: Optional[str] = None


@dataclass
class LintReport:
    """Lint 报告"""

    issues: List[LintIssue] = field(default_factory=list)
    checks_passed: int = 0
    checks_failed: int = 0

    @property
    def has_errors(self) -> bool:
        return any(i.severity == Severity.ERROR for i in self.issues)

    @property
    def has_warnings(self) -> bool:
        return any(i.severity == Severity.WARNING for i in self.issues)


class ProjectLinter:
    """项目一致性检查器"""

    STATUS_FILE = MODERN_STATUS_PATH
    AGENT_TASKS_DIR = ".agent/agent-tasks"
    RULES_DIR = ".agent/rules"
    CLI_FILE = "src/dimcause/cli.py"

    # 任务 ID → CLI 命令映射
    TASK_CLI_MAP = {
        "D1": "why",
        "T1": "trace",
        "H1": "history",
        "H2": "timeline",
        "S3": "migrate",
    }

    def __init__(self, project_root: Path = None):
        self.root = project_root or Path.cwd()
        self.report = LintReport()

    def run_all_checks(self, fix: bool = False) -> LintReport:
        """运行所有检查"""
        if fix:
            self._fix_task_card_completeness()

        self._check_task_card_completeness()
        self._check_status_evidence_chain()
        self._check_rule_file_validity()
        self._check_cli_implementation()
        self._check_file_path_existence()
        return self.report

    def _fix_task_card_completeness(self):
        """修复: 创建缺失的任务卡"""
        status_path = self._resolve_status_file()
        if status_path is None:
            return

        content = status_path.read_text(encoding="utf-8")
        task_ids = self._extract_task_ids(
            content, modern=status_path == self.root / self.STATUS_FILE
        )

        agent_tasks_dir = self.root / self.AGENT_TASKS_DIR
        agent_tasks_dir.mkdir(parents=True, exist_ok=True)

        existing_task_files = set()
        for md_file in agent_tasks_dir.glob("*.md"):
            # Fix regex: use [^_]+ to avoid greedy matching
            match = re.match(r"agent_([^_]+)_", md_file.name, re.IGNORECASE)
            if match:
                existing_task_files.add(match.group(1).upper())

        missing = task_ids - existing_task_files
        for task_id in missing:
            filename = f"agent_{task_id.lower()}_placeholder.md"
            path = agent_tasks_dir / filename
            if not path.exists():
                path.write_text(
                    f"""---
status: Planned
priority: P2
---

# Agent Task {task_id}: Placeholder

## 背景
Generated by dimc lint --fix

## 目标
TBD
""",
                    encoding="utf-8",
                )
                # print(f"Fix: Created {filename}") # Logic here runs silent, reports later

    def _check_task_card_completeness(self):
        """检查 1: 任务卡完整性"""
        check_name = "任务卡完整性"

        status_path = self._resolve_status_file()
        if status_path is None:
            # ... error ...
            return

        content = status_path.read_text(encoding="utf-8")
        task_ids = self._extract_task_ids(
            content, modern=status_path == self.root / self.STATUS_FILE
        )

        agent_tasks_dir = self.root / self.AGENT_TASKS_DIR
        existing_task_files = set()

        if agent_tasks_dir.exists():
            for md_file in agent_tasks_dir.glob("*.md"):
                # FIX: Regex was greedy (\w includes _)
                match = re.match(r"agent_([^_]+)_", md_file.name, re.IGNORECASE)
                if match:
                    existing_task_files.add(match.group(1).upper())

        # ... logic ...
        missing = task_ids - existing_task_files
        if missing:
            for task_id in missing:
                self.report.issues.append(
                    LintIssue(
                        check=check_name,
                        severity=Severity.WARNING,
                        message=f"任务 {task_id} 在 STATUS 中存在，但没有对应的任务卡文件",
                        suggestion=f"创建 {self.AGENT_TASKS_DIR}/agent_{task_id.lower()}_xxx.md",
                    )
                )
            self.report.checks_failed += 1
        else:
            self.report.checks_passed += 1

    # ... (rest of methods)

    def _check_status_evidence_chain(self):
        """检查 2: 状态证据链"""
        check_name = "状态证据链"

        status_path = self._resolve_status_file()
        if status_path is None:
            return  # 已在检查 1 中报告

        content = status_path.read_text(encoding="utf-8")

        # 查找标记为 Done 的任务
        done_pattern = r"\|\s*\*?\*?(\w+)\*?\*?\s*\|[^|]+\|[^|]+\|\s*\*?\*?Done\*?\*?\s*\|"
        done_tasks = re.findall(done_pattern, content, re.IGNORECASE)

        cli_file = self.root / self.CLI_FILE
        if not cli_file.exists():
            return

        cli_content = cli_file.read_text(encoding="utf-8")

        for task_id in done_tasks:
            task_id = task_id.upper()
            if task_id in self.TASK_CLI_MAP:
                cli_cmd = self.TASK_CLI_MAP[task_id]
                # 检查 CLI 命令是否存在（简单的字符串匹配）
                if f"def {cli_cmd}(" not in cli_content and f"'{cli_cmd}'" not in cli_content:
                    self.report.issues.append(
                        LintIssue(
                            check=check_name,
                            severity=Severity.ERROR,
                            message=f"任务 {task_id} 标记为 Done，但 CLI 命令 `dimc {cli_cmd}` 不存在",
                            file_path=cli_file,
                            suggestion="检查任务状态是否正确，或实现对应的 CLI 命令",
                        )
                    )

        self.report.checks_passed += 1

    def _resolve_status_file(self) -> Optional[Path]:
        return resolve_status_file(self.root)

    def _check_rule_file_validity(self):
        """检查 3: 规则文件合法性"""
        check_name = "规则文件合法性"

        rules_dir = self.root / self.RULES_DIR
        if not rules_dir.exists():
            self.report.issues.append(
                LintIssue(
                    check=check_name,
                    severity=Severity.INFO,
                    message=f"规则目录不存在: {self.RULES_DIR}",
                )
            )
            return

        issues_found = False
        for mdc_file in rules_dir.glob("*.mdc"):
            content = mdc_file.read_text(encoding="utf-8")

            # 检查 YAML frontmatter
            if not content.startswith("---"):
                self.report.issues.append(
                    LintIssue(
                        check=check_name,
                        severity=Severity.WARNING,
                        message=f"规则文件缺少 YAML frontmatter: {mdc_file.name}",
                        file_path=mdc_file,
                        suggestion="添加 YAML 头部（以 --- 开始和结束）",
                    )
                )
                issues_found = True
                continue

            # 检查必要的 YAML 字段
            required_fields = ["description", "globs"]
            frontmatter_match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
            if frontmatter_match:
                frontmatter = frontmatter_match.group(1)
                for field in required_fields:
                    if f"{field}:" not in frontmatter:
                        self.report.issues.append(
                            LintIssue(
                                check=check_name,
                                severity=Severity.WARNING,
                                message=f"规则文件缺少必要字段 '{field}': {mdc_file.name}",
                                file_path=mdc_file,
                            )
                        )
                        issues_found = True

        if not issues_found:
            self.report.checks_passed += 1

    def _check_cli_implementation(self):
        """检查 4: CLI 实现验证"""
        check_name = "CLI 实现验证"

        cli_file = self.root / self.CLI_FILE
        if not cli_file.exists():
            self.report.issues.append(
                LintIssue(
                    check=check_name,
                    severity=Severity.ERROR,
                    message=f"CLI 文件不存在: {self.CLI_FILE}",
                    file_path=cli_file,
                )
            )
            self.report.checks_failed += 1
            return

        cli_content = cli_file.read_text(encoding="utf-8")

        # 检查核心功能是否存在
        required_functions = [
            ("up", "每日开工"),
            ("down", "每日收工"),
            ("job_start", "任务开始"),
            ("job_end", "任务结束"),
            ("search", "搜索"),
            ("why", "因果分析"),
        ]

        for func_name, desc in required_functions:
            if f"def {func_name}(" not in cli_content:
                self.report.issues.append(
                    LintIssue(
                        check=check_name,
                        severity=Severity.ERROR,
                        message=f"核心 CLI 函数缺失: {func_name} ({desc})",
                        file_path=cli_file,
                    )
                )

        self.report.checks_passed += 1

    def _check_file_path_existence(self):
        """检查 5: 文件路径存在性"""
        check_name = "文件路径存在性"

        agent_tasks_dir = self.root / self.AGENT_TASKS_DIR
        if not agent_tasks_dir.exists():
            return

        # 正则匹配文件路径引用
        path_pattern = r"`((?:src/|docs/|\.agent/)[^`]+)`"

        for md_file in agent_tasks_dir.glob("*.md"):
            content = md_file.read_text(encoding="utf-8")

            for match in re.finditer(path_pattern, content):
                ref_path = match.group(1)
                full_path = self.root / ref_path

                if not full_path.exists():
                    self.report.issues.append(
                        LintIssue(
                            check=check_name,
                            severity=Severity.WARNING,
                            message=f"引用的路径不存在: {ref_path}",
                            file_path=md_file,
                            suggestion="检查路径是否正确，或更新引用",
                        )
                    )

        self.report.checks_passed += 1

    def _extract_task_ids(self, content: str, modern: bool = False) -> set:
        """从 STATUS 文件中提取 legacy agent-task 使用的紧凑任务 ID。"""
        return {task_id.upper() for task_id in extract_compact_task_ids(content, modern=modern)}


def run_lint(
    project_root: Path = None, fix: bool = False, target_path: Optional[Path] = None
) -> LintReport:
    """运行 Lint 检查"""
    linter = ProjectLinter(target_path or project_root)
    return linter.run_all_checks(fix=fix)


def format_report(report: LintReport) -> str:
    """格式化 Lint 报告为可读字符串"""
    lines = ["## 📋 Dimcause Lint Report", ""]

    if not report.issues:
        lines.append("✅ 所有检查通过！项目状态一致。")
        return "\n".join(lines)

    # 按严重程度分组
    errors = [i for i in report.issues if i.severity == Severity.ERROR]
    warnings = [i for i in report.issues if i.severity == Severity.WARNING]
    infos = [i for i in report.issues if i.severity == Severity.INFO]

    if errors:
        lines.append(f"### ❌ 错误 ({len(errors)})")
        for issue in errors:
            lines.append(f"- **[{issue.check}]** {issue.message}")
            if issue.suggestion:
                lines.append(f"  💡 {issue.suggestion}")
        lines.append("")

    if warnings:
        lines.append(f"### ⚠️ 警告 ({len(warnings)})")
        for issue in warnings:
            lines.append(f"- **[{issue.check}]** {issue.message}")
            if issue.suggestion:
                lines.append(f"  💡 {issue.suggestion}")
        lines.append("")

    if infos:
        lines.append(f"### ℹ️ 信息 ({len(infos)})")
        for issue in infos:
            lines.append(f"- **[{issue.check}]** {issue.message}")
        lines.append("")

    # 统计
    lines.append("### 📊 统计")
    lines.append(f"- 检查通过: {report.checks_passed}")
    lines.append(f"- 检查失败: {report.checks_failed}")
    lines.append(f"- 问题总数: {len(report.issues)}")

    return "\n".join(lines)
